App\Request\UploadImageRequest:
  properties:
    uploadedFile:
      - Image:
          #mimeTypesMessage: "this id not message"
          maxSize: 2m
          maxSizeMessage: "Image size over 2M"

App\Request\CreateInteractionRequest:
  properties:
    userID:
      - NotBlank: ~
    animeID:
      - NotBlank: ~
    type:
      - NotBlank: ~

App\Request\CreateInteractionEpisodeRequest:
  properties:
    userID:
      - NotBlank: ~
    episodeID:
      - NotBlank: ~
    type:
      - NotBlank: ~

App\Request\CreateAnimeRequest:
  properties:
    name:
      - NotBlank: ~
    categoryID:
      - NotBlank: ~
    mainImage:
      - NotBlank: ~
    description:
      - NotBlank: ~

App\Request\CreateCategoryRequest:
  properties:
    name:
      - NotBlank: ~
    description:
      - NotBlank: ~

App\Request\CreateCommentRequest:
  properties:
    userID:
      - NotBlank: ~
    animeID:
      - NotBlank: ~
    comment:
      - NotBlank: ~

App\Request\CreateInteractionCommentRequest:
  properties:
    userID:
      - NotBlank: ~
    commentID:
      - NotBlank: ~
    type:
      - NotBlank: ~

App\Request\CreateInteractionCommentEpisodeRequest:
  properties:
    userID:
      - NotBlank: ~
    commentID:
      - NotBlank: ~
    type:
      - NotBlank: ~

App\Request\CreateEpisodeRequest:
  properties:
    animeID:
      - NotBlank: ~
    seasonNumber:
      - NotBlank: ~
    episodeNumber:
      - NotBlank: ~
    description:
      - NotBlank: ~
    image:
      - NotBlank: ~

App\Request\CreateFavouriteRequest:
  properties:
    animeID:
      - NotBlank: ~
    userID:
      - NotBlank: ~
    categoryID:
      - NotBlank: ~
    
App\Request\CreateFollowRequest:
  properties:
    userID:
      - NotBlank: ~
    friendID:
      - NotBlank: ~
    
App\Request\CreateImageRequest:
  properties:
    image:
      - NotBlank: ~
    animeID:
      - NotBlank: ~
    
App\Request\CreateRatingRequest:
  properties:
    userID:
      - NotBlank: ~
    animeID:
      - NotBlank: ~
    rateValue:
      - NotBlank: ~
 
App\Request\CreateRatingEpisodeRequest:
  properties:
    userID:
      - NotBlank: ~
    episodeID:
      - NotBlank: ~
    rateValue:
      - NotBlank: ~

App\Request\CreateCommentEpisodeRequest:
  properties:
    userID:
      - NotBlank: ~
    episodeID:
      - NotBlank: ~
    comment:
      - NotBlank: ~


App\Request\UpdateInteractionRequest:
  properties:
    userID:
      - NotBlank: ~
    animeID:
      - NotBlank: ~
    type:
      - NotBlank: ~
    
App\Request\UpdateInteractionEpisodeRequest:
  properties:
    userID:
      - NotBlank: ~
    episodeID:
      - NotBlank: ~
    type:
      - NotBlank: ~

App\Request\UpdateAnimeRequest:
  properties:
    name:
      - NotBlank: ~
    categoryID:
      - NotBlank: ~
    mainImage:
      - NotBlank: ~
    description:
      - NotBlank: ~

App\Request\UpdateCategoryRequest:
  properties:
    name:
      - NotBlank: ~
    description:
      - NotBlank: ~

App\Request\UpdateCommentRequest:
  properties:
    userID:
      - NotBlank: ~
    animeID:
      - NotBlank: ~
    comment:
      - NotBlank: ~

App\Request\UpdateEpisodeRequest:
  properties:
    animeID:
      - NotBlank: ~
    seasonNumber:
      - NotBlank: ~
    episodeNumber:
      - NotBlank: ~
    description:
      - NotBlank: ~
    image:
      - NotBlank: ~

App\Request\UpdateImageRequest:
  properties:
    image:
      - NotBlank: ~
    animeID:
      - NotBlank: ~

App\Request\UpdateRatingRequest:
  properties:
    userID:
      - NotBlank: ~
    animeID:
      - NotBlank: ~
    rateValue:
      - NotBlank: ~
      
App\Request\UpdateRatingEpisodeRequest:
  properties:
    userID:
      - NotBlank: ~
    episodeID:
      - NotBlank: ~
    rateValue:
      - NotBlank: ~

App\Request\UpdateCommentEpisodeRequest:
  properties:
    userID:
      - NotBlank: ~
    episodeID:
      - NotBlank: ~
    comment:
      - NotBlank: ~

App\Request\UpdateInteractionCommentRequest:
  properties:
    userID:
      - NotBlank: ~
    commentID:
      - NotBlank: ~
    type:
      - NotBlank: ~

App\Request\UpdateInteractionCommentEpisodeRequest:
  properties:
    userID:
      - NotBlank: ~
    commentID:
      - NotBlank: ~
    type:
      - NotBlank: ~